// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmheymrnjuqlmzyjcgap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtaGV5bXJuanVxbG16eWpjZ2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDAwNTAsImV4cCI6MjA2ODA3NjA1MH0.bFz20i51NLSL3XmBKKcKOPPO2mMX_H_WlhdeMyhlj8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});